ID_FIELD = "id"
FIO_FIELD = "fio"
PHONE_FIELD = "phone"
DEPARTMENT_FIELD = "department"
JOB_FIELD = "job"
ID_WORKER_FIELD = "id_worker"
ID_JOB_FIELD = "id_job"
ID_DEPARTMENT_FIELD = "id_department"

NEW_VALUE = "new_value"
OLD_VALUE = "old_value"

VALIDATE_ASS_KEY = "ass_to_validate"
VALIDATE_DEP_KEY = "dep_to_validate"
VALIDATE_WORK_KEY = "work_to_validate"
VALIDATE_JOB_KEY = "job_to_validate"
